### ISSUE TITLE
Pagination not working when "Store minified HTML in cache" enabled

### ISSUE THREAD

**Issue by ondrejvysek** [rblinde/grav-plugin-html-minifier#1]
when the plugin is enabled and stored in the cache, pagination is broken - it displays still the same page and does not switch to the particular page. compression mode does not change the result.

**Comment by rblinde** [comment]
I have published a new release fixing your issue. Should be added to GPM shortly.

**Comment by ondrejvysek** [comment]
I owe you a cup of coffee! Thanks
